# Generated by Django 3.1.6 on 2021-05-14 17:59

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meme_file', models.ImageField(upload_to=posts.models._meme_path)),
                ('identifier', models.CharField(max_length=40, unique=True)),
                ('moderation_status', models.CharField(choices=[('W', 'Waiting for Moderation'), ('M', 'Moderating'), ('A', 'Approved'), ('D', 'Denied')], default='W', max_length=2)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('meme_labels', models.TextField(blank=True, null=True)),
                ('meme_text', models.TextField(blank=True, null=True)),
                ('meme_labelled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='posts.post')),
            ],
        ),
    ]
