# Generated by Django 3.1.6 on 2021-05-21 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210521_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='meme_search',
            field=models.TextField(blank=True, null=True),
        ),
    ]
