# Generated by Django 3.1.6 on 2021-05-14 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postdenialreason',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_denial_reasons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationstatus',
            name='denial_reason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moderation.postdenialreason'),
        ),
        migrations.AddField(
            model_name='moderationstatus',
            name='moderator_moderating',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_moderating', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationstatus',
            name='moderator_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moderationstatus',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='posts.post'),
        ),
        migrations.AlterUniqueTogether(
            name='postdenialreason',
            unique_together={('description', 'moderator')},
        ),
        migrations.AlterUniqueTogether(
            name='moderationstatus',
            unique_together={('post', 'result', 'moderator_result')},
        ),
    ]
